***Task 1***

In [24]:
#Create a following list: 6,11,24,8,45,25,60
import numpy as np
A = np.array([2,6,11,24,8,45,25,60])
print("Array",A)

#Delete last element of the list
A = np.delete(A,6)
print("Deleting last element",A)

#Add 22 value at index 3 of the list
A = np.insert(A,3,22)
print("Adding 22 at index 3",A)

#Create an ndarray object by using list
np.ndarray = np.array(A)
print(np.ndarray)

Array [ 2  6 11 24  8 45 25 60]
Deleting last element [ 2  6 11 24  8 45 60]
Adding 22 at index 3 [ 2  6 11 22 24  8 45 60]
[ 2  6 11 22 24  8 45 60]


***Task 2***

In [32]:
#Create a 2-D array and a 3-D. Split the 2-D array into three 2-D arrays along rows.
import numpy as np
# 1. Create a 2-D array
array_2d = np.arange(24).reshape(6, 4)
print("2-D Array")
print(array_2d)
print("\n")

# 2. Create a 3-D array
array_3d = np.arange(24).reshape(2, 3, 4)
print("3-D Array")
print(array_3d)
print("\n")


# 3. Split the 2-D array into three 2-D arrays along rows
split_arrays = np.split(array_2d, 3)
print("Splitted Arrays:")
print("Array 1 \n",split_arrays[0])
print("Array 1 \n",split_arrays[1])
print("Array 1 \n",split_arrays[2])

2-D Array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


3-D Array
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


Splitted Arrays:
Array 1 
 [[0 1 2 3]
 [4 5 6 7]]
Array 1 
 [[ 8  9 10 11]
 [12 13 14 15]]
Array 1 
 [[16 17 18 19]
 [20 21 22 23]]


***Task 3***

In [26]:
#Find the indexes where the values are even
import numpy as np
A = np.array([ 6, 11, 24, 22, 8, 45, 25])
even_indices = np.where(A % 2 == 0)
print("Array:", A)
print("even values:", even_indices)

Array: [ 6 11 24 22  8 45 25]
even values: (array([0, 2, 3, 4]),)


***Task 4***

In [29]:
#Create a filter array that will return only values higher than 55
import numpy as np
A = np.array([ 2,6, 11, 24, 22, 56, 59, 67])
filter_array = A[A > 55]
print("Array:", A)
print("Values higher than 55:", filter_array)


Array: [ 2  6 11 24 22 56 59 67]
Values higher than 55: [56 59 67]


***Task 5***

In [34]:
#Create a 3x3 matrix with values ranging from 2 to 10, convert array to a float type. Write a python program to find the maximum and minimum value to flattened array.
# 3x3 matrix with values 2–10
matrix = np.arange(2, 11).reshape(3, 3)
print("Matrix:\n", matrix)

# Convert to float
matrix_float = matrix.astype(float)
print("Float Matrix:\n", matrix_float)

# Flatten and find max & min
flat = matrix_float.flatten()
print("Flattened array:", flat)
print("Max value:", np.max(flat))
print("Min value:", np.min(flat))


Matrix:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
Float Matrix:
 [[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
Flattened array: [ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
Max value: 10.0
Min value: 2.0


***Task 6***

In [49]:
import random

# Create a list of 150 random numbers between 1 and 500
random_numbers = [random.randint(1, 100) for _ in range(150)]

# 1. Show all numbers in the list
print("1. Full list of 150 random numbers:")
print(random_numbers)

# 2. Find and show all even numbers
even_numbers = [num for num in random_numbers if num % 2 == 0]
print("\n2. Even numbers in the list:")
print(even_numbers)

# 3. Find and show all prime numbers
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

prime_numbers = [num for num in random_numbers if is_prime(num)]
print("\n3. Prime numbers in the list:")
print(prime_numbers)

# 4. Function to print multiples of a given number
def find_multiples(numbers_list, given_number):
    print(f"\n4. Multiples of {given_number}:")
    multiples = [num for num in numbers_list if num % given_number == 0]

    if multiples:
        print(multiples)
    else:
        print(f"No multiples of {given_number} were found in the list.")

find_multiples(random_numbers, 5)


1. Full list of 150 random numbers:
[72, 25, 69, 80, 19, 17, 40, 29, 63, 25, 36, 36, 10, 80, 76, 66, 82, 11, 62, 45, 74, 32, 18, 48, 96, 41, 92, 80, 33, 80, 80, 10, 21, 43, 87, 29, 50, 71, 64, 27, 29, 27, 87, 13, 21, 59, 73, 42, 89, 97, 30, 17, 59, 50, 91, 68, 52, 67, 69, 70, 72, 98, 45, 57, 81, 27, 37, 78, 70, 83, 88, 85, 64, 34, 100, 41, 64, 1, 47, 92, 34, 82, 2, 61, 33, 57, 18, 84, 94, 32, 9, 84, 51, 4, 100, 78, 53, 7, 12, 23, 21, 95, 73, 17, 33, 97, 56, 36, 3, 54, 43, 13, 37, 96, 51, 92, 74, 80, 67, 16, 87, 82, 43, 71, 19, 38, 17, 88, 15, 48, 19, 86, 6, 6, 81, 89, 61, 99, 56, 78, 76, 29, 84, 84, 47, 39, 98, 25, 73, 7]

2. Even numbers in the list:
[72, 80, 40, 36, 36, 10, 80, 76, 66, 82, 62, 74, 32, 18, 48, 96, 92, 80, 80, 80, 10, 50, 64, 42, 30, 50, 68, 52, 70, 72, 98, 78, 70, 88, 64, 34, 100, 64, 92, 34, 82, 2, 18, 84, 94, 32, 84, 4, 100, 78, 12, 56, 36, 54, 96, 92, 74, 80, 16, 82, 38, 88, 48, 86, 6, 6, 56, 78, 76, 84, 84, 98]

3. Prime numbers in the list:
[19, 17, 29, 11, 41, 4